import type { Metadata } from "next";
import { GeistSans, GeistMono } from 'geist/font';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ModalProvider } from "@/components/ModalProvider";
import { ClientLayoutWrapper } from "@/components/ClientLayoutWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <ModalProvider>
          <ClientLayoutWrapper>
            {children}
          </ClientLayoutWrapper>
        </ModalProvider>
      </body>
    </html>
  );
}
